# Generated by Django 4.0.5 on 2022-06-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_data',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Дата выполнения'),
        ),
    ]
